version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file: ./api-gateway/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_CLIENT=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    networks:
      - my-network

  identity-service:
    build: ./identity-service
    env_file: ./identity-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_CLIENT=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    networks:
      - my-network

  post-service :
    build: ./post-service
    env_file: ./post-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_CLIENT=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    networks:
      - my-network


  media-service :
    build: ./media-service
    env_file: ./media-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_CLIENT=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    networks:
      - my-network


  search-service :
    build: ./search-service
    env_file: ./search-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_CLIENT=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    networks:
      - my-network


  redis :
    image: redis:alpine
    ports:
    - "6379:6379"
    networks:
      - my-network

  rabbitmq :
    image : rabbitmq:3-management
    ports :
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test : ["CMD", "rabbitmq-diagnostics","-q","ping"]
      interval : 30s
      timeout : 10s
      retries : 5
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
    