#use nodejs 18 with official alpine linux as base image

FROM node:18-alpine

WORKDIR /use/src/app

COPY package*.json ./

RUN npm ci --only=production 

COPY . .

EXPOSE 3003

CMD ["node","src/server.js"]